server:
  port:
    8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      - id: sms-verification_get
        uri: lb://demo
        predicates:
          - Path= /v1/sms-verification/**
          - Method=GET
        filters:
          - SetPath=/demo/v1/sms-verification/

      - id: sms-verification-post
        uri: lb://demo
        predicates:
          - Path= /sms-verification/**
          - Method=POST
        filters:
          - SetPath=/demo/v1/sms-verification/







