spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=liquibase_test2&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none