spring:
  datasource:
    url: jdbc:h2:mem:testdb?createDatabaseIfNotExist=true
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none